#services:
#  # Our PostgreSQL database
#  db:
#    # Using the latest PostgreSQL image
#    image: postgres:latest
#    ports:
#      - "5432:5432"
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: changemeinprod!
#
#  # Database management interface
#  adminer:
#    image: adminer:latest
#    restart: always
#    ports:
#      - 8888:8080

version: '3.8'

services:
  quiz:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: changemeinprod!
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres-quiz
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: